apiVersion: v1
kind: Template
metadata:
  name: testangularapp
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: testangularapp
    name: testangularapp
  spec:
    tags:
    - name: "testangularapp"
- apiVersion: "v1"
  kind: "BuildConfig"
  metadata:
    name: "testangularapp"
  spec:
    source:
      git:
        uri: https://github.com/shanpagoti/ui-template.git
    strategy: 
      type: "Docker"
    output:
      to:
        kind: "ImageStreamTag"
        name: "testangularapp:latest"
    triggers:
    - generic:
        secret: b725254e6534fd70
      type: Generic
    - type: ConfigChange
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftWebConsole
    creationTimestamp: null
    generation: 7
    labels:
      app: testangularapp
    name: testangularapp
  spec:
    replicas: 1
    selector:
      app: testangularapp
      deploymentconfig: testangularapp
    strategy:
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftWebConsole
        creationTimestamp: null
        labels:
          app: testangularapp
          deploymentconfig: testangularapp
      spec:
        containers:
        - env:
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          image: testangularapp/testangularapp@sha256:f5f80e5c582c0e5ed010a9057ce5c6458c31f4e28c652d0e1f9397cd543c2b31
          imagePullPolicy: Always
          name: testangularapp
          resources: {}
          terminationMessagePath: /dev/termination-log
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - testangularapp
        from:
          kind: ImageStreamTag
          name: testangularapp:latest
      type: ImageChange